# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "yl61626.ca-central-1.aws"
user = "ketkimude"
password = "Ketki@137"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"

